argo-cd:

  global:
    image:
      repository: argoproj/argocd
#      tag: v2.2.3
  dex:
    enabled: false

  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 85
      targetMemoryUtilizationPercentage: 85

#    extraArgs:
#      - --parallelismlimit 10

    env:
      - name: ARGOCD_EXEC_TIMEOUT
        value: 300s

    metrics:
      enabled: false
      serviceMonitor:
        enabled: false

    extraContainers:
      # Custom hack to expose secret helm values over localhost http
      - name: secret-loader
        image: httpd:2.4
        ports:
          - name: secret-loader
            containerPort: 80
            protocol: TCP
        volumeMounts:
          - mountPath: /usr/local/apache2/htdocs/
            name: helm-values

    volumes:
      - name: helm-values
        secret:
          secretName: argo-helm-values
          optional: true

    resources:
      requests:
        cpu: 1000m
        memory: 2048Mi
      limits:
        cpu: 2000m
        memory: 2048Mi


  server:
    ## Server service configuration
    service:
      # -- Server service type
      type: NodePort
    # ingress:
    #   enabled: true
    #   annotations:
    #     kubernetes.io/ingress.class: nginx
    #     cert-manager.io/cluster-issuer: vault-issuer
    #     cert-manager.io/common-name: argo.rsr.net
    #   hosts:
    #     - argo.rsr.net
    #   tls:
    #     - hosts:
    #         - "argo.rsr.net"
    #       secretName: argo-cert-tls
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: git
          url: https://github.com/amit-gueta/home-k0s.git
          passwordSecret:
            name: deployment-git-repo-credentials
            key: password
          usernameSecret:
            name: deployment-git-repo-credentials
            key: username
      # Following the guide at https://argoproj.github.io/argo-cd/user-guide/diffing/#system-level-configuration
      resource.customizations: |
        admissionregistration.k8s.io/MutatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/clientConfig/caBundle

    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
    autoscaling:
      enabled: false
      minReplicas: 2
      targetCPUUtilizationPercentage: 85
      targetMemoryUtilizationPercentage: 85
    resources:
      requests:
        cpu: 100m
        memory: 105Mi

  controller:
    enableStatefulSet: true
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false

    args:
      repoServerTimeoutSeconds: 300




