apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: home-assistant
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infrastructure/home-assistant
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.revision }}
    helm:
      # valueFiles:
      #   - values.yaml
      values: |
        service:
          main:
            type: LoadBalancer
            ports:
              http:
                port: 8123
  syncPolicy: {}
# automated:
#   prune: true
#   selfHeal: true
# syncOptions:
#   - CreateNamespace=true
#   - ApplyOutOfSyncOnly=true
