apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infrastructure/longhorn
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.revision }}
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
