loki-stack:
  test_pod:
    image: bats/bats:v1.1.0
    pullPolicy: IfNotPresent


  loki:
    enabled: true
    isDefault: true
    readinessProbe:
      httpGet:
        path: /ready
        port: http-metrics
      initialDelaySeconds: 45
    livenessProbe:
      httpGet:
        path: /ready
        port: http-metrics
      initialDelaySeconds: 45
    datasource:
      jsonData: {}

  promtail:
    enabled: true
    config:
      lokiAddress: http://{{ .Release.Name }}:3100/loki/api/v1/push

  fluent-bit:
    enabled: false

  grafana:
    enabled: true
    service:
      type: LoadBalancer
    sidecar:
      datasources:
        enabled: true
        maxLines: 1000
    image:
      tag: 8.3.5

  prometheus:
    enabled: true
    isDefault: false
    datasource:
      jsonData: {}

